package myudf.featureUDTF;

import com.aliyun.odps.udf.ExecutionContext;
import com.aliyun.odps.udf.UDFException;
import com.aliyun.odps.udf.UDTF;
import com.aliyun.odps.udf.annotation.Resolve;
import com.jayway.jsonpath.JsonPath;
import com.jayway.jsonpath.ReadContext;

// TODO define input and output types, e.g. "string,string->string,bigint".
@Resolve({"string,string,string,string,string,string,string,string,string,string->string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string," +
        "string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string"})
public class FeatureReportUDTF extends UDTF {

    static String[] columns1 = {
            "TdScore",
            "RegisterDays",
            "OrderCompleteLastThreeMonths",
            "OverdueOrderLastThreeMonths",
            "MaxLatefeeLastThreeMonths",
            "MaxOrderAmountLastThreeMonths",
            "MaxRepayAmountLastThreeMonths",
            "MaxApplyDaysLastSixMonths",
            "AvgAmountLastSixMonths",
            "MaxOrderAmountLastSixMonths",
            "OrderNumLastSixMonths",
            "AvgLatefeeLastSixMonths",
            "AvgRepayAmountLastSixMonths",
            "AvgOverdueDaysLastSixMonths",
            "OverdueOrderLastSixMonths",
            "OverdueOrderRateLastSixMonths",
            "MaxLatefeeLastSixMonths",
            "MaxRepayAmountLastSixMonths",
            "OrderRepayLastOneYear",
            "MaxApplyDaysLastOneYear",
            "AvgAmountLastOneYear",
            "MaxOrderAmountLastOneYear",
            "OrderCompleteLastOneYear",
            "OrderNumLastOneYear",
            "AvgLatefeeLastOneYear",
            "AvgRepayAmountLastOneYear",
            "AvgOverdueDaysLastOneYear",
            "RegisterLoanRate",
            "OverdueOrderLastOneYear",
            "OverdueOrderRateLastOneYear",
            "MaxLatefeeLastOneYear",
            "MaxRepayAmountLastOneYear",
            "LastRepaymentToNowDays",
            "LastLoanToNowDays",
            "AvgLoanCredit",
            "HistoryLoanCount",
            "HistoryOverdueCount",
            "HistoryOverdueDaysTotal",
            "AvgHistoryOverdueDaysTotal",
            "HistoryOverdueMaxDays",
            "HistoryLoanMaxCredit",
            "TdHitsItemCount",
            "FirstLoanToNowDays",
            "XyOneMonthOrganizationDebitFailCount",
            "AvgAmountLastOneMonth",
            "AvgAmountRepayLastOneMonth",
            "XyHistoryOrganizationDebitFailCount",
            "XyLoanBehaviorScore",
            "XyApplyAccessScore",
            "XyOneMonthOrganizationDebitSuccessCount",
            "XyLoanFinishOrderCount",
            "XyHistoryOrganizationDebitSuccessCount",
            "XyLoanOverdueMOneOrderCount",
            "XyBehaviorConfidence",
            "XyMindCreditConfidence",
            "XyThreeMonthOrganizationLoanCount",
            "XyOneMonthOrganizationLoanCount",
            "XySixMonthOrganizationLoanCount",
            "XyLatelyLoanTime",
            "XyLoanOrderCountTotal",
            "XyConsFinancialInstitutionsAvgCredit",
            "XyConsFinancialInstitutionsMaxCredit",
            "XyNetworkInstitutionsAvgCredit",
            "XyNetworkInstitutionsMaxCredit",
            "XyHitNetInstitutionCount",
            "XyHitUseConsProductCount",
            "XyHitUseConsInstitutionCount",
            "XyHitConsInstitutionCount",
            "XyHitUseNetProductCount",
            "XyHitUseNetInstitutionCount",
            "XyAdviceCredit",
            "XyCreditLoanTime",
            "XyHitLoanInstitutionCount",
            "XyLatelyInstitutionSearchTime",
            "MaxAmountLastOneMonth",
            "MaxAmountRepayLastOneMonth",
            "MinAmountLastOneMonth",
            "MinAmountRepayLastOneMonth",
            "AvgAmountLastThreeMonth",
            "AvgAmountRepayLastThreeMonth",
            "OrderGapLastThreeMonth",
            "OrderNumLastThreeMonths",
            "AvgLatefeeLastThreeMonths",
            "Td7DayPlatformCount",
            "WorkNumLastSixMonths",
            "ShzxLoanAmountNum",
            "Td3MonthIdCardInMultipleHomeAddress",
            "Td1MonthIdCardInMultipleDevice",
            "ShzxFirstApplyDay",
            "Td6MonthPlatformP2PCount",
            "Td6MonthPlatformFenqiPlatformCount",
            "Td3MonthPlatformFenqiPlatformCount",
            "Td3MonthPlatformP2PCount",
            "ShzxCreditLoanSum",
            "Td6MonthPlatformSmallLoanCompanyCount",
            "Td3MonthPlatformSmallLoanCompanyCount",
            "Td24MonthPlatformSmallLoanCompanyCount",
            "Td12MonthPlatformSmallLoanCompanyCount",
            "Td18MonthPlatformSmallLoanCompanyCount",
            "ShzxLoanAmountBalance",
            "Td1MonthPlatformSmallLoanCompanyCount",
            "ShzxRepayAmountPerMonth",
            "Td1MonthPlatformP2PCount",
            "Td18MonthPlatformP2PCount",
            "ShzxCurrentOverdueAmount",
            "ShzxMaxOverdueAmount",
            "Td24MonthPlatformP2PCount",
            "Td12MonthPlatformP2PCount",
            "ShzxMaxOverdueStage",
            "Td7DayPlatformP2PCount",
            "ShzxOverdueCountLastOneMonth",
            "Td1MonthPlatformFenqiPlatformCount",
            "Td7DayPlatformFenqiPlatformCount",
            "Td12MonthPlatformFenqiPlatformCount",
            "Td18MonthPlatformFenqiPlatformCount",
            "Td24MonthPlatformFenqiPlatformCount",
            "ShzxOverdueCountLastThreeMonth",
            "ShzxOverdueCountLastSixMonth",
            "ShzxLoanRiskSelectCountLastOneMonth",
            "ShzxLoanRiskSelectCountLastThreeMonth",
            "ShzxLoanRiskSelectCountLastSixMonth",
            "ShzxLoanManageCountLastOneMonth",
            "ShzxLoanManageCountLastThreeMonth",
            "ShzxLoanManageCountLastOneMonthSix",
            "ShzxLoanApplyCountLastSixMonth",
            "Td12MonthPlatformConsumeFinancialCompanyCount",
            "Td3MonthPlatformConsumeFinancialCompanyCount",
            "Td24MonthPlatformConsumeFinancialCompanyCount",
            "Td18MonthPlatformConsumeFinancialCompanyCount",
            "Td6MonthPlatformConsumeFinancialCompanyCount",
            "Td1MonthPlatformConsumeFinancialCompanyCount",
            "Td12MonthPlatformThirdServiceCount",
            "Td18MonthPlatformThirdServiceCount",
            "Td24MonthPlatformThirdServiceCount",
            "Td7DayIdCardInMultipleDevice",
            "AvgPeriodOrderAmountLastOneMonth",
            "AvgAmountRepayLastOneMonthPeriod",
            "MaxOrderAmountLastOneMonthPeriod",
            "Td7DayPlatformSmallLoanCompanyCount",
            "Td3MonthIdCardInMultiplePhone",
            "MaxRepayAmountLastOneMonthPeriod",
            "Td18MonthPlatformBankConsumeFinancialCompanyCount",
            "Td24MonthPlatformBankConsumeFinancialCompanyCount",
            "MinOrderAmountLastOneMonthPeriod",
            "Td12MonthPlatformBankConsumeFinancialCompanyCount",
            "Td6MonthPlatformBankConsumeFinancialCompanyCount",
            "MinRepayAmountLastOneMonthPeriod",
            "TdHitsItemAddRate",
            "MaxApplyDaysLastThreeMonthPeriod",
            "AvgAmountLastThreeMonthPeriod",
            "OrderNumLastThreeMonthPeriod",
            "AvgLatefeeLastThreeMonthsPeriod",
            "AvgRepayAmountLastThreeMonthsPeriod",
            "OrderCompleteLastThreeMonthsPeriod",
            "OverdueOrderLastThreeMonthsPeriod",
            "MaxLatefeeLastThreeMonthsPeriod",
            "MaxOrderAmountLastThreeMonthPeriod",
            "MaxRepayAmountLastThreeMonthsPeriod",
            "MaxApplyDaysLastSixMonthPeriod",
            "TdScoreAddRate",
            "AvgAmountLastSixMonthPeriod",
            "MaxOrderAmountLastSixMonthPeriod",
            "OrderNumLastSixMonthPeriod",
            "AvgLatefeeLastSixMonthsPeriod",
            "Td24MonthPlatformCountDiff",
            "AvgRepayAmountLastSixMonthsPeriod",
            "AvgOverdueDaysLastSixMonthsPeriod",
            "OverdueOrderLastSixMonthsPeriod",
            "OverdueOrderRateLastSixMonthsPeriod",
            "MaxLatefeeLastSixMonthsPeriod",
            "MaxRepayAmountLastSixMonthsPeriod",
            "OrderRepayLastOneYearPeriod",
            "Td18MonthPlatformCountDiff",
            "Td18MonthPlatformCountAddRate",
            "MaxApplyDaysLastOneYearPeriod",
            "AvgAmountLastOneYearPeriod",
            "Td12MonthPlatformCountDiff",
            "Td12MonthPlatformCountAddRate",
            "MaxOrderAmountLastOneYearPeriod",
            "OrderCompleteLastOneYearPeriod",
            "OrderNumLastOneYearPeriod",
            "AvgLatefeeLastOneYearPeriod",
            "AvgRepayAmountLastOneYearPeriod",
            "AvgOverdueDaysLastOneYearPeriod",
            "OverdueOrderLastOneYearPeriod",
            "OverdueOrderRateLastOneYearPeriod",
            "MaxLatefeeLastOneYearPeriod",
            "MaxRepayAmountLastOneYearPeriod",
            "CreditCardTypeInterestCount",
            "Order3MonthNotNightCount",
            "Td3MonthIdCardInMultipleApply",
            "Td1MonthIdCardInMultipleDeviceTotal",
            "Td7DayIdCardInMultipleDeviceTotal",
            "OrderNumbersNotNight3month",
            "AvgNumberCreditCard",
            "CreditCardWdtransCnt",
            "CreditCardTypeInterestAmt",
            "UserAppVersion",
            "UserDeviceName",
            "UserDeviceOsVersion",
            "CreditCardNowdtransWkCnt",
            "CreditCardLimitAvailPct",
            "CreditCardWdtransWkCnt",
            "CreditCardCategoryElecconsCnt",
            "CreditCardCategoryTechnoCnt",
            "OrderOverdueDay",
            "OrderRepayDays",
            "OrderLoanDelayCount",
            "RepaymentCount"
    };

    static String[] columns2 = {
            "BingjianBjScore",
            "BingjianHighRiskScore",
            "BingjianIckScore",
            "BingjianPropertyScore",
            "BingjianPurchaseScore",
            "BingjianRecentExpenseScore",
            "BingjianStabilityScore"};

    static String[] columns3 = {
            "KexinLevel1Count"  ,
            "KexinLevel2Count",
            "KexinLevel3Count" ,
            "KexinRiskDesc" ,
            "KexinRiskLevel"  ,
            "KexinScore"
    };

    @Override
    public void setup(ExecutionContext ctx) throws UDFException {

    }

    @Override
    public void process(Object[] args) throws UDFException {
        String report = (String) args[7];

        ReadContext rct = JsonPath.parse(report);
        Object[] feature = new Object[35];
        // feature 660 ~ 694
        for(int i = 0; i<=34; i++) {
            try {
                int j = i+660;
                feature[i] = rct.read("$." + j + ".value") + "";
            }catch(Exception e) {
                feature[i] = "";
            }
        }
        //
        Object[] feature1 = new Object[columns1.length];
        for(int i=0;i <columns1.length;i++){
            try {

                feature1[i] = rct.read("$." + columns1[i]  ) + "";
            }catch(Exception e) {
                feature1[i] = "";
            }
        }
        Object[] feature2 = new Object[columns2.length];
        for(int i=0;i <columns2.length;i++){
            try {

                feature2[i] = rct.read("$." + columns2[i]  ) + "";
            }catch(Exception e) {
                feature2[i] = "";
            }
        }
        Object[] feature3 = new Object[columns3.length];
        for(int i=0;i <columns3.length;i++){
            try {

                feature3[i] = rct.read("$." + columns3[i]  ) + "";
            }catch(Exception e) {
                feature3[i] = "";
            }
        }
        forward(args[0], args[1],args[2],args[3],args[4],args[5],args[6],args[8],
                feature[0],feature[1], feature[2], feature[3], feature[4], feature[5], feature[6], feature[7], feature[8], feature[9], feature[10], feature[11], feature[12], feature[13], feature[14], feature[15], feature[16], feature[17], feature[18], feature[19], feature[20], feature[21], feature[22], feature[23], feature[24], feature[25], feature[26], feature[27], feature[28], feature[29], feature[30], feature[31], feature[32], feature[33], feature[34],
                feature1[0],
                feature1[1],
                feature1[2],
                feature1[3],
                feature1[4],
                feature1[5],
                feature1[6],
                feature1[7],
                feature1[8],
                feature1[9],
                feature1[10],
                feature1[11],
                feature1[12],
                feature1[13],
                feature1[14],
                feature1[15],
                feature1[16],
                feature1[17],
                feature1[18],
                feature1[19],
                feature1[20],
                feature1[21],
                feature1[22],
                feature1[23],
                feature1[24],
                feature1[25],
                feature1[26],
                feature1[27],
                feature1[28],
                feature1[29],
                feature1[30],
                feature1[31],
                feature1[32],
                feature1[33],
                feature1[34],
                feature1[35],
                feature1[36],
                feature1[37],
                feature1[38],
                feature1[39],
                feature1[40],
                feature1[41],
                feature1[42],
                feature1[43],
                feature1[44],
                feature1[45],
                feature1[46],
                feature1[47],
                feature1[48],
                feature1[49],
                feature1[50],
                feature1[51],
                feature1[52],
                feature1[53],
                feature1[54],
                feature1[55],
                feature1[56],
                feature1[57],
                feature1[58],
                feature1[59],
                feature1[60],
                feature1[61],
                feature1[62],
                feature1[63],
                feature1[64],
                feature1[65],
                feature1[66],
                feature1[67],
                feature1[68],
                feature1[69],
                feature1[70],
                feature1[71],
                feature1[72],
                feature1[73],
                feature1[74],
                feature1[75],
                feature1[76],
                feature1[77],
                feature1[78],
                feature1[79],
                feature1[80],
                feature1[81],
                feature1[82],
                feature1[83],
                feature1[84],
                feature1[85],
                feature1[86],
                feature1[87],
                feature1[88],
                feature1[89],
                feature1[90],
                feature1[91],
                feature1[92],
                feature1[93],
                feature1[94],
                feature1[95],
                feature1[96],
                feature1[97],
                feature1[98],
                feature1[99],
                feature1[100],
                feature1[101],
                feature1[102],
                feature1[103],
                feature1[104],
                feature1[105],
                feature1[106],
                feature1[107],
                feature1[108],
                feature1[109],
                feature1[110],
                feature1[111],
                feature1[112],
                feature1[113],
                feature1[114],
                feature1[115],
                feature1[116],
                feature1[117],
                feature1[118],
                feature1[119],
                feature1[120],
                feature1[121],
                feature1[122],
                feature1[123],
                feature1[124],
                feature1[125],
                feature1[126],
                feature1[127],
                feature1[128],
                feature1[129],
                feature1[130],
                feature1[131],
                feature1[132],
                feature1[133],
                feature1[134],
                feature1[135],
                feature1[136],
                feature1[137],
                feature1[138],
                feature1[139],
                feature1[140],
                feature1[141],
                feature1[142],
                feature1[143],
                feature1[144],
                feature1[145],
                feature1[146],
                feature1[147],
                feature1[148],
                feature1[149],
                feature1[150],
                feature1[151],
                feature1[152],
                feature1[153],
                feature1[154],
                feature1[155],
                feature1[156],
                feature1[157],
                feature1[158],
                feature1[159],
                feature1[160],
                feature1[161],
                feature1[162],
                feature1[163],
                feature1[164],
                feature1[165],
                feature1[166],
                feature1[167],
                feature1[168],
                feature1[169],
                feature1[170],
                feature1[171],
                feature1[172],
                feature1[173],
                feature1[174],
                feature1[175],
                feature1[176],
                feature1[177],
                feature1[178],
                feature1[179],
                feature1[180],
                feature1[181],
                feature1[182],
                feature1[183],
                feature1[184],
                feature1[185],
                feature1[186],
                feature1[187],
                feature1[188],
                feature1[189],
                feature1[190],
                feature1[191],
                feature1[192],
                feature1[193],
                feature1[194],
                feature1[195],
                feature1[196],
                feature1[197],
                feature1[198],
                feature1[199],
                feature1[200],
                feature1[201],
                feature1[202],
                feature1[203],
                feature1[204],
                feature1[205],
                feature1[206],
                feature1[207],
                feature1[208],
                feature2[0],
                feature2[1],
                feature2[2],
                feature2[3],
                feature2[4],
                feature2[5],
                feature2[6],
                feature3[0],
                feature3[1],
                feature3[2],
                feature3[3],
                feature3[4],
                feature3[5],
                 args[9]);
    }

    @Override
    public void close() throws UDFException {

    }

}